### ISSUE TITLE
publish to npm

### ISSUE THREAD

**Issue by marionebl** [asciinema/vt#3]
To make work on alternative asciicast renderers easier this could be published to npm.

**Comment by marionebl** [comment]
I went ahead and published a subset of `asciinema.player.asciicast` instead: https://github.com/marionebl/load-asciicast

**Comment by sickill** [comment]
Awesome :) Btw, we're also working on publishing [npm package for asciicast2gif](https://github.com/asciinema/asciicast2gif/pull/25).
